DROP TABLE IF EXISTS `person`;
CREATE TABLE `person`(
  id int PRIMARY KEY AUTO_INCREMENT,
  `updateTime` VARCHAR(20) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
)DEFAULT CHARSET=utf8;


INSERT INTO person(id)VALUES (1);
INSERT INTO person(id)VALUES (2);
INSERT INTO person(id)VALUES (3);

